config/routes.rb
Rails.application.routes.draw do
	root 'breweries#index'
		
	resources :styles
  	resources :memberships
  	resources :beer_clubs
  	resources :users do
		post 'toggle_ban', on: :member
	end

  	resources :beers
  	resources :breweries
  
  	resources :ratings, only: [:index, :new, :create, :destroy]  
  
  	get 'signin', to: 'sessions#new'
  	get 'signup', to: 'users#new'  
	delete 'signout', to: 'sessions#destroy'	
	
		
	
	resources :places, only:[:index, :show]
	post 'places', to:'places#search'
	  
  	resource :session, only: [:new, :create, :destroy]    
end

app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage
	
	validates :username, uniqueness: true,
								length:{minimum:3, maximum: 15}
	validates :password, length:{minimum: 4}
	validates_format_of :password, :with => /\A.*[A-Z].*\z/i
	validates_format_of :password, :with => /\A.*[0-9].*\z/i
								
	
	has_many :ratings, dependent: :destroy
	has_many :beers, through: :ratings
	has_many :memberships,  dependent: :destroy
	has_many :beer_clubs, through: :memberships
	
	has_secure_password
	
	
	def favorite_beer
		return nil if ratings.empty?
		ratings.order(score: :desc).limit(1).first.beer
	end
	
	def favorite_style
		favorite :style
	end
	
	def favorite_brewery
		favorite :brewery
	end	
	
	def favorite(category)
		return nil if ratings.empty?

		rated = ratings.map{ |r| r.beer.send(category) }.uniq
		rated.sort_by { |item| -rating_of(category, item) }.first
	end	

	def self.top(n)
		User.all.sort_by{ |u| -(u.ratings.count) }.first(n)
	end	
	
	def rating_of(category, item)
    ratings_of = ratings.select{ |r| r.beer.send(category)==item }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :toggle_ban]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and current_user == @user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if current_user == @user
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
      session[:user_id] = nil
    end
  end
  
  def toggle_ban
	 @user.update_attribute(:banned, !@user.banned) if current_user.admin
	 msg = 'User has been banned' if @user.banned
	 msg = 'Ban has been removed' if !@user.banned
	 redirect_to @user, notice: msg
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <% if @user.new_record? %>
  	<div class="field">
    	<%= f.label :username %><br>
    	<%= f.text_field :username %>
  	</div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= "#{@user.username}" %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> Rated beers </th>
      <th> Total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if user.admin? and user.banned? %>
            <span class="label label-info">banned</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong><%= @user.username %></strong>
  <% if @user.banned %>
  	<i> (Banned)</i>
  <% end %>
</p>

<% if current_user and current_user.admin and current_user != @user %>
	<% if @user.banned %>
		<%= link_to "remove ban", toggle_ban_user_path(@user.id), method: :post, class: "btn btn-danger" %>
	<% else %>
		<%= link_to "ban", toggle_ban_user_path(@user.id), method: :post, class: "btn btn-danger" %>
	<% end %>
<% end %>


<p>
	<% if not @user.ratings.empty? %>
 		Favorite beer: <%= link_to @user.favorite_beer, @user.favorite_beer %> <br>
 		Favorite style: <%= link_to @user.favorite_style.name, @user.favorite_style %> <br>
 		Favorite brewery: <%= link_to @user.favorite_brewery.name, @user.favorite_brewery %>
	<% end %>
</p>


<p>
	<% if @user.ratings.empty? %>
 		User has not rated any beers yet!
	<% else %>
 		Has rated <%= pluralize(@user.ratings.count, 'beer', 'beers')%>,
 		Average score: <%= round @user.average_rating%> <br>
 	<%end%>
</p>

<ul>
	<% @user.ratings.each do |rating| %>
		<% if current_user == rating.user %>
			<li><%= rating%> <%= link_to 'Delete', rating, method: :delete %></li>
		<% end %>
	<% end %>
</ul>

<p>
	User is a member of the following beer clubs: <br>
	<% @user.beer_clubs.each do |beer_club| %>
		<%= link_to beer_club.name, beer_club %> <br>
	<% end %>
</p>

<% if current_user == @user %>
	<%= link_to 'Edit', edit_user_path(@user) %>
	<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', users_path %>